library(readr)
project_all <- read_csv("Desktop/coding/mycodesource/Multicampus/3조자료/project/R/project_all.csv")
View(project_all)
project_all
cov(project_all)
corr<-round(cor(project_all),3)
attach(project_all)
#install.packages('psych')
library(psych)
pairs.panels(project_all)
st <-data.frame(project_all)
plot(st)
#install.packages('corrplot')
library(corrplot)
par(family="AppleGothic")
corrplot(corr,method='shade', tl.col='black',shade.col = NA, tl.srt = 45)
corrplot(corr, type='lower', cl.ratio=0.2, col=COL2('PuOr',10),method='shade',shade.col=NA, tl.col='black',tl.srt=45, order='hclust', addrect = 2)
